driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: false

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: freebsd-11
  - name: fedora-29
  - name: opensuse-leap-42
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: openjdk-6
    includes:
      - amazon-linux
      - centos-6
      - centos-7
    run_list:
      - recipe[test::openjdk6]
  - name: openjdk-7
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - freebsd-11
      - opensuse-leap-42
      - ubuntu-16.04
    run_list:
      - recipe[test::openjdk7]
  - name: openjdk-8
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-9
      - fedora-29
      - freebsd-11
      - opensuse-leap-42
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::openjdk8]
  - name: openjdk-11
    includes:
      - centos-7
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::openjdk11]
    verifier:
      inspec_tests:
        - test/integration/openjdk-11
  - name: oracle-8
    run_list:
      - recipe[test::oracle8]
  - name: oracle-direct
    run_list:
      - recipe[test::oracle_direct]
    verifier:
      inspec_tests:
        - test/integration/oracle-8
  - name: openjdk-direct
    run_list:
      - recipe[test::openjdk_direct]
  - name: oracle-rpm-8
    includes:
      - centos-6
      - centos-7
      - fedora-29
    run_list:
      - recipe[test::oracle_rpm8]
    verifier:
      inspec_tests:
        - test/integration/oracle-8
  - name: adoptopenjdk-8-openj9
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::adoptopenjdk-8-openj9]
    verifier:
      inspec_tests:
        - test/integration/adoptopenjdk
      attrs:
        - test/integration/adoptopenjdk/attributes/adoptopenjdk-8-openj9.yml
  - name: adoptopenjdk-10-openj9
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::adoptopenjdk-10-openj9]
    verifier:
      inspec_tests:
        - test/integration/adoptopenjdk
      attrs:
        - test/integration/adoptopenjdk/attributes/adoptopenjdk-10-openj9.yml
  - name: adoptopenjdk-10-hotspot
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::adoptopenjdk-10-hotspot]
    verifier:
      inspec_tests:
        - test/integration/adoptopenjdk
      attrs:
        - test/integration/adoptopenjdk/attributes/adoptopenjdk-10-hotspot.yml
  - name: adoptopenjdk-11-hotspot
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::adoptopenjdk-11-hotspot]
    verifier:
      inspec_tests:
        - test/integration/adoptopenjdk
      attrs:
        - test/integration/adoptopenjdk/attributes/adoptopenjdk-11-hotspot.yml
  - name: adoptopenjdk-11-openj9
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::adoptopenjdk-11-openj9]
    verifier:
      inspec_tests:
        - test/integration/adoptopenjdk
      attrs:
        - test/integration/adoptopenjdk/attributes/adoptopenjdk-11-openj9.yml
  - name: adoptopenjdk-11-openj9-large-heap
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::adoptopenjdk-11-openj9-large-heap]
    verifier:
      inspec_tests:
        - test/integration/adoptopenjdk
      attrs:
        - test/integration/adoptopenjdk/attributes/adoptopenjdk-11-openj9-large-heap.yml
  - name: adoptopenjdk-removal-11-openj9
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::remove-adoptopenjdk-11-openj9]
    verifier:
      inspec_tests:
        - test/integration/remove-adoptopenjdk
      attrs:
        - test/integration/adoptopenjdk/attributes/adoptopenjdk-11-openj9.yml
  - name: corretto-8
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::corretto8]
  - name: corretto-11
    includes:
      - amazon-linux
      - centos-6
      - centos-7
      - debian-8
      - debian-9
      - ubuntu-16.04
      - ubuntu-18.04
    run_list:
      - recipe[test::corretto11]
