name              'java'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Recipes and resources for installing Java and managing certificates'
source_url        'https://github.com/sous-chefs/java'
issues_url        'https://github.com/sous-chefs/java/issues'
chef_version      '>= 15.3'
version           '10.0.0'

supports 'debian'
supports 'ubuntu'
supports 'centos'
supports 'redhat'
supports 'scientific'
supports 'fedora'
supports 'amazon'
supports 'oracle'
supports 'freebsd'
supports 'suse'
supports 'opensuseleap'

depends 'line'
